// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package projects

import (
	"context"
)

type Querier interface {
	GetProjectByProjectKey(ctx context.Context, projectKey string) (OnboardingProject, error)
}

var _ Querier = (*Queries)(nil)
