// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package session

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OnboardingSession struct {
	SessionID  uuid.UUID        `json:"session_id"`
	ScenarioID uuid.UUID        `json:"scenario_id"`
	UserID     uuid.UUID        `json:"user_id"`
	Status     string           `json:"status"`
	StartedAt  pgtype.Timestamp `json:"started_at"`
	FinishedAt pgtype.Timestamp `json:"finished_at"`
}
