// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package session

import (
	"context"
)

type Querier interface {
	ChangeSessionStatus(ctx context.Context, arg ChangeSessionStatusParams) (OnboardingSession, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (OnboardingSession, error)
	GetSessionByScenarioAndUser(ctx context.Context, arg GetSessionByScenarioAndUserParams) (OnboardingSession, error)
}

var _ Querier = (*Queries)(nil)
