// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package session

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ChangeSessionStatus(ctx context.Context, arg ChangeSessionStatusParams) (OnboardingSession, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (OnboardingSession, error)
	GetSessionByScenarioAndUser(ctx context.Context, arg GetSessionByScenarioAndUserParams) (OnboardingSession, error)
	SelectSessionById(ctx context.Context, id uuid.UUID) (OnboardingSession, error)
}

var _ Querier = (*Queries)(nil)
