// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package session

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const changeSessionStatus = `-- name: ChangeSessionStatus :one
UPDATE "OnboardingSession"
SET "status" = $1, "finished_at" = $2
WHERE "session_id" = $3
RETURNING session_id, scenario_id, user_id, status, started_at, finished_at
`

type ChangeSessionStatusParams struct {
	Status     string           `json:"status"`
	FinishedAt pgtype.Timestamp `json:"finished_at"`
	SessionID  uuid.UUID        `json:"session_id"`
}

func (q *Queries) ChangeSessionStatus(ctx context.Context, arg ChangeSessionStatusParams) (OnboardingSession, error) {
	row := q.db.QueryRow(ctx, changeSessionStatus, arg.Status, arg.FinishedAt, arg.SessionID)
	var i OnboardingSession
	err := row.Scan(
		&i.SessionID,
		&i.ScenarioID,
		&i.UserID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO "OnboardingSession"
  ("session_id", "scenario_id", "user_id", "status", "started_at", "finished_at")
VALUES
  ($1, $2, $3, $4, $5, $6)
RETURNING session_id, scenario_id, user_id, status, started_at, finished_at
`

type CreateSessionParams struct {
	SessionID  uuid.UUID        `json:"session_id"`
	ScenarioID uuid.UUID        `json:"scenario_id"`
	UserID     uuid.UUID        `json:"user_id"`
	Status     string           `json:"status"`
	StartedAt  pgtype.Timestamp `json:"started_at"`
	FinishedAt pgtype.Timestamp `json:"finished_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (OnboardingSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.SessionID,
		arg.ScenarioID,
		arg.UserID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i OnboardingSession
	err := row.Scan(
		&i.SessionID,
		&i.ScenarioID,
		&i.UserID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getSessionByScenarioAndUser = `-- name: GetSessionByScenarioAndUser :one
SELECT session_id, scenario_id, user_id, status, started_at, finished_at
FROM "OnboardingSession"
WHERE "scenario_id" = $1 AND "user_id" = $2
`

type GetSessionByScenarioAndUserParams struct {
	ScenarioID uuid.UUID `json:"scenario_id"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) GetSessionByScenarioAndUser(ctx context.Context, arg GetSessionByScenarioAndUserParams) (OnboardingSession, error) {
	row := q.db.QueryRow(ctx, getSessionByScenarioAndUser, arg.ScenarioID, arg.UserID)
	var i OnboardingSession
	err := row.Scan(
		&i.SessionID,
		&i.ScenarioID,
		&i.UserID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
