// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package session

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const changeSessionStatus = `-- name: ChangeSessionStatus :one
UPDATE onboarding.sessions
SET "status" = $1, "finished_at" = $2
WHERE "id" = $3 AND "status" = 'active'
RETURNING id, scenario_id, user_id, status, started_at, finished_at
`

type ChangeSessionStatusParams struct {
	Status     string             `json:"status"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) ChangeSessionStatus(ctx context.Context, arg ChangeSessionStatusParams) (OnboardingSession, error) {
	row := q.db.QueryRow(ctx, changeSessionStatus, arg.Status, arg.FinishedAt, arg.ID)
	var i OnboardingSession
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.UserID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO onboarding.sessions
  ("id", "scenario_id", "user_id", "status", "started_at", "finished_at")
VALUES
  ($1, $2, $3, $4, $5, $6)
RETURNING id, scenario_id, user_id, status, started_at, finished_at
`

type CreateSessionParams struct {
	ID         uuid.UUID          `json:"id"`
	ScenarioID uuid.UUID          `json:"scenario_id"`
	UserID     string             `json:"user_id"`
	Status     string             `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (OnboardingSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.ScenarioID,
		arg.UserID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i OnboardingSession
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.UserID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getSessionByScenarioAndUser = `-- name: GetSessionByScenarioAndUser :one
SELECT id, scenario_id, user_id, status, started_at, finished_at
FROM onboarding.sessions
WHERE "id" = $1 AND "user_id" = $2
`

type GetSessionByScenarioAndUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"user_id"`
}

func (q *Queries) GetSessionByScenarioAndUser(ctx context.Context, arg GetSessionByScenarioAndUserParams) (OnboardingSession, error) {
	row := q.db.QueryRow(ctx, getSessionByScenarioAndUser, arg.ID, arg.UserID)
	var i OnboardingSession
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.UserID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const selectSessionById = `-- name: SelectSessionById :one
SELECT id, scenario_id, user_id, status, started_at, finished_at
FROM onboarding.sessions
WHERE "id" = $1
`

func (q *Queries) SelectSessionById(ctx context.Context, id uuid.UUID) (OnboardingSession, error) {
	row := q.db.QueryRow(ctx, selectSessionById, id)
	var i OnboardingSession
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.UserID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
