// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package event

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OnboardingEvent struct {
	EventID    uuid.UUID        `json:"event_id"`
	SessionID  uuid.UUID        `json:"session_id"`
	StepID     pgtype.UUID      `json:"step_id"`
	Type       string           `json:"type"`
	Data       []byte           `json:"data"`
	OccurredAt pgtype.Timestamp `json:"occurred_at"`
	ReceivedAt pgtype.Timestamp `json:"received_at"`
}
