// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package event

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
WITH "active_session" AS (
  SELECT "id"
  FROM onboarding.sessions
  WHERE "id" = $2
    AND "status" = 'active'
  FOR UPDATE
)
INSERT INTO onboarding.events
  ("id", "session_id", "step_id", "type", "data", "occurred_at", "received_at")
SELECT
  $1, $2, $3, $4, $5, $6, $7
FROM "active_session"
RETURNING id, session_id, step_id, type, data, occurred_at, received_at
`

type CreateEventParams struct {
	ID         uuid.UUID          `json:"id"`
	SessionID  uuid.UUID          `json:"session_id"`
	StepID     pgtype.UUID        `json:"step_id"`
	Type       string             `json:"type"`
	Data       []byte             `json:"data"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (OnboardingEvent, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.ID,
		arg.SessionID,
		arg.StepID,
		arg.Type,
		arg.Data,
		arg.OccurredAt,
		arg.ReceivedAt,
	)
	var i OnboardingEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StepID,
		&i.Type,
		&i.Data,
		&i.OccurredAt,
		&i.ReceivedAt,
	)
	return i, err
}

const getEventById = `-- name: GetEventById :one
SELECT id, session_id, step_id, type, data, occurred_at, received_at
FROM onboarding.events
WHERE "id" = $1
`

func (q *Queries) GetEventById(ctx context.Context, id uuid.UUID) (OnboardingEvent, error) {
	row := q.db.QueryRow(ctx, getEventById, id)
	var i OnboardingEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StepID,
		&i.Type,
		&i.Data,
		&i.OccurredAt,
		&i.ReceivedAt,
	)
	return i, err
}
