// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package event

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (OnboardingEvent, error)
	GetEventById(ctx context.Context, eventID uuid.UUID) (OnboardingEvent, error)
}

var _ Querier = (*Queries)(nil)
