// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package event

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO "OnboardingEvent"
  ("event_id", "session_id", "step_id", "type", "data", "occurred_at", "received_at")
VALUES
  ($1, $2, $3, $4, $5, $6, $7)
RETURNING event_id, session_id, step_id, type, data, occurred_at, received_at
`

type CreateEventParams struct {
	EventID    uuid.UUID        `json:"event_id"`
	SessionID  uuid.UUID        `json:"session_id"`
	StepID     pgtype.UUID      `json:"step_id"`
	Type       string           `json:"type"`
	Data       []byte           `json:"data"`
	OccurredAt pgtype.Timestamp `json:"occurred_at"`
	ReceivedAt pgtype.Timestamp `json:"received_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (OnboardingEvent, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.EventID,
		arg.SessionID,
		arg.StepID,
		arg.Type,
		arg.Data,
		arg.OccurredAt,
		arg.ReceivedAt,
	)
	var i OnboardingEvent
	err := row.Scan(
		&i.EventID,
		&i.SessionID,
		&i.StepID,
		&i.Type,
		&i.Data,
		&i.OccurredAt,
		&i.ReceivedAt,
	)
	return i, err
}

const getEventById = `-- name: GetEventById :one
SELECT event_id, session_id, step_id, type, data, occurred_at, received_at
FROM "OnboardingEvent"
WHERE "event_id" = $1
`

func (q *Queries) GetEventById(ctx context.Context, eventID uuid.UUID) (OnboardingEvent, error) {
	row := q.db.QueryRow(ctx, getEventById, eventID)
	var i OnboardingEvent
	err := row.Scan(
		&i.EventID,
		&i.SessionID,
		&i.StepID,
		&i.Type,
		&i.Data,
		&i.OccurredAt,
		&i.ReceivedAt,
	)
	return i, err
}
