// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package token

import (
	"context"
)

type Querier interface {
	GetTokenByHash(ctx context.Context, hash []byte) (OnboardingScenarioTestToken, error)
}

var _ Querier = (*Queries)(nil)
