// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package scenario

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ApplyStepOrder(ctx context.Context, arg ApplyStepOrderParams) (int64, error)
	CreateStep(ctx context.Context, arg CreateStepParams) (CreateStepRow, error)
	DeleteStep(ctx context.Context, arg DeleteStepParams) (DeleteStepRow, error)
	GetNextStepNumber(ctx context.Context, scenarioID uuid.UUID) (int32, error)
	// WHAT???
	GetStepByID(ctx context.Context, arg GetStepByIDParams) (GetStepByIDRow, error)
	ListStepsByScenarioID(ctx context.Context, scenarioID uuid.UUID) ([]ListStepsByScenarioIDRow, error)
	LockActiveStep(ctx context.Context, arg LockActiveStepParams) (LockActiveStepRow, error)
	LockActiveStepsByScenarioID(ctx context.Context, scenarioID uuid.UUID) ([]LockActiveStepsByScenarioIDRow, error)
	// Reordering must run in one transaction after LockActiveStepsByScenarioID.
	// The first query moves every active position above the current range so that
	// assigning positions 1..N cannot violate the partial unique index.
	MoveStepsOutOfOrderRange(ctx context.Context, scenarioID uuid.UUID) error
	UpdateStep(ctx context.Context, arg UpdateStepParams) (UpdateStepRow, error)
}

var _ Querier = (*Queries)(nil)
